### ISSUE TITLE
handle repeating elements programmatically

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/pdap.io#124]
right now we're 100% static, so there's a bunch of duplication in the page headers. it makes maintenance brittle.

back in the day, I would have done this with PHP—it could just as easily be done with JavaScript and AJAX.

- [ ] header content
- [ ] nav (replicate "current page" functionality)
- [ ] footer (while we're in there, make the copyright date update automatically)

**Comment by benpolinsky** [comment]
Hello. Just found this project and would like to contribute. 
I could take this to get started.

You could use ajax/fetch api to repeat the sections, but it'd be a bit hacky. 

I'd usually use something like [handlebars](https://handlebarsjs.com/) for this which has support for [partials](https://handlebarsjs.com/guide/partials.html#basic-partials). This would require a quick build step before running/deploying. If that's not desired, I could try to whip something up 

It's unfortunate HTML doesn't have native partial support.

**Comment by josh-chamberlain** [comment]
Thanks for leaving a comment @benpolinsky ! Nice to have you here. Hm, handlebars is cool but we're in the process of building our [design system](https://github.com/Police-Data-Accessibility-Project/design-system/) and component library with Vue and Tailwind UI. Adding another templating engine, however lightweight, feels like the wrong move...any way you're willing/able to work on this in that paradigm?

**Comment by benpolinsky** [comment]
> Adding another templating engine, however lightweight, feels like the wrong move... any way you're willing/able to work on this in that paradigm?

Absolutely - that makes sense to me. Only a bit of experience with Vue, but I can figure it out.

**Comment by benpolinsky** [comment]
(Working on it, btw - should be ready today or tomorrow at the latest)

**Comment by benpolinsky** [comment]
#134
