### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by zgoulson** [Police-Data-Accessibility-Project/PDAP.io#13]
- [ ] Hyperlink colors are pretty difficult to read
- [ ] Paragraph text isn't very discernable compared to header text
- [ ] Add dark/light theme toggle

**Comment by milespratt** [comment]
Started working on this.

**Comment by milespratt** [comment]
@josh-chamberlain @zgoulson 

Regarding the following:

- Hyperlink colors are pretty difficult to read
- Paragraph text isn't very discernible compared to header text

Do we have a consensus on the changes we want? I can start with some more contrast on the yellow and making the header text larger if that works.

**Comment by josh-chamberlain** [comment]
@milespratt Do what you want! As long as it's readable we're good.
