### ISSUE TITLE
Replace `FlexContainer`, `GridContainer`, and `GridItem` components with Tailwind utility classes on native elements

### ISSUE THREAD

**Issue by joshuagraber** [Police-Data-Accessibility-Project/pdap.io#164]
Initially, we were planning to use exported components from [design-system](https://github.com/Police-Data-Accessibility-Project/design-system). However, since we are now using Tailwind in the client app, these components could cause more headache than not.

- [x] Update the current config in `tailwind.config.js` to use the tailwind config exported by `design-system`
   - use [the data sources app as a reference](https://github.com/Police-Data-Accessibility-Project/data-sources-app/blob/main/client/tailwind.config.js)
- [x] Replace all instances of `FlexContainer`, `GridContainer`, and `GridItem` with TailwindCSS utility classes

## Acceptance Criteria
The app must match what's on `pdap.dev`

**Comment by phillitrOSU** [comment]
https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/373
