### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/PDAP.io#24]
![Screen Shot 2021-06-02 at 8 51 12 PM](https://user-images.githubusercontent.com/30379833/120569613-44d98d00-c3e4-11eb-97bd-6945b67d4ed9.png)

- [x] add a `Donate on Patreon` button that looks the same sits next to the existing button and points to https://patreon.com/pdap
- [x] rename the Donate button to `Donate on Paypal`
- [ ] add a "Partners" section with DoltHub on it (logo attached). For the love of our eyes, it should be white!
- [x] add a "Privacy Policy" link: https://docs.pdap.io/meta/policy/pdap-privacy-policy 
- [x] remove the Slack link and add a Discord icon: https://discord.gg/cn2ZpVTdw7
- [x] github link should point here instead: https://github.com/Police-Data-Accessibility-Project

↑ these two were fixed in #33, there are some comments in the code and below

[dolthub.svg.zip](https://github.com/Police-Data-Accessibility-Project/PDAP.io/files/6722282/dolthub.svg.zip)

**Comment by Pythonidaer** [comment]
Some of the other issues I noticed with Josh:

1.  Renaming the Donate button to Donate on Paypal breaks the button width in the navbar.
         - Change the text in Console to see what I mean. Donate / on / Paypal stacks up vertically over each word.

I am not familiar with the design system, but I one potential root cause of this is below:
```
.nav-module--nav__menu--33GJJ {
    display: grid;
    grid-auto-flow: column;
    grid-auto-columns: -webkit-min-content;
    **grid-auto-columns: min-content;**
    white-space: nowrap;
    grid-gap: 3rem;
    height: 100%;
    align-items: center;
    z-index: 10;
}
```

Changing   `grid-auto-columns: min-content;` to `  grid-auto-columns: initial;` should resolve this
          - Note I am not sure if this affects any other items in the repo, it appears to be for the nav-bar grid system.

**Comment by Pythonidaer** [comment]
2. We were unable to successfully duplicate the `<PaypalDonate/>` component to create a `<PatreonDonate/>` button.
          - The Paypal component is a form, containing a button. This prevents the button from being right-clicked -> 'open new tab'
                   - This is irrelevant for now, it's just for documentation.
          - By comparison, the PatreonDonate component might just need to be an <a> tag. This can be styled exactly like the button, though I am not experienced to know if that is weird or not to have a button and an anchor link styled the same way.
                   - What are the thoughts here? Whoever created the PaypalDonate component may know best on this. Idk.

**Comment by milespratt** [comment]
@josh-chamberlain should the DoltHub logo function and look like the other icons in the footer?
