### ISSUE TITLE
User friendly interface for interacting with acquired data

### ISSUE THREAD

**Issue by RenatoLopes771** [Police-Data-Accessibility-Project/PDAP.io#53]
Having normal users rely on Dolt to search for data is bad for the "accessibility" of the project. As it stands right now, I believe only people like journalists and those that work with this data would go through the trouble of learning our database (dolt hub) and its language (SQL) to acquire information.

Altough the implementation is not necessary right now, we should think of a user friendly interface users can interact with. I also propose that for this interface you really shouldn't need a documentation to use. Think of how on wikipedia you can just search "Osama Bin Laden" and find about him in a few clicks.

**Comment by josh-chamberlain** [comment]
This is now on our [official roadmap](https://github.com/orgs/Police-Data-Accessibility-Project/projects/17): https://github.com/Police-Data-Accessibility-Project/planning/issues/144

I'm going to close this issue as a duplicate.
